"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownRight, CalendarDays, Scale, Target } from "lucide-react";
import { PageLayout, PageHeader } from "@/components/layout/page-layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type CheckIn = { weeklyWeight?: string; sundayWeight?: string; waist?: string; steps?: string; strength?: string; alcohol?: string; recordedAt: string };
export default function ProgressPage() {
  const [checkins, setCheckins] = useState<CheckIn[]>([]);
  useEffect(() => { setCheckins(JSON.parse(localStorage.getItem("athlos-checkins") ?? "[]")); }, []);
  const latest = checkins.at(-1); const first = checkins[0];
  const change = useMemo(() => first && latest && Number(first.weeklyWeight) && Number(latest.weeklyWeight) ? Number(latest.weeklyWeight) - Number(first.weeklyWeight) : null, [first, latest]);
  const points = checkins.map((item, index) => ({ x: checkins.length === 1 ? 50 : 6 + (index * 88) / (checkins.length - 1), y: 88 - Math.max(0, Math.min(70, (Number(item.weeklyWeight || 0) - 80) * 4)) }));
  const path = points.map((point, index) => `${index === 0 ? "M" : "L"} ${point.x} ${point.y}`).join(" ");
  return <PageLayout><PageHeader tag="TENDENCIAS" title="Tu progreso" description="Aquí miramos la dirección, no las oscilaciones de un día." />{!latest ? <EmptyProgress /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Scale} label="Peso medio actual" value={`${latest.weeklyWeight} kg`} detail={change === null ? "Primer registro" : `${change <= 0 ? "−" : "+"}${Math.abs(change).toFixed(1)} kg desde el inicio`} /><Metric icon={Target} label="Cintura actual" value={`${latest.waist} cm`} detail="Registrada en el último check-in" /><Metric icon={CalendarDays} label="Semanas registradas" value={`${checkins.length}`} detail="Cada dato mejora el análisis" /><Metric icon={ArrowDownRight} label="Pasos medios" value={latest.steps ? Number(latest.steps).toLocaleString("es-ES") : "—"} detail="Última semana" /></section><Card className="mt-7 border-slate-200 shadow-sm"><CardHeader><CardTitle>Peso medio semanal</CardTitle><p className="mt-1 text-sm text-slate-500">Se dibujará una tendencia más fiable conforme registres semanas.</p></CardHeader><CardContent className="pb-6"><div className="h-64 w-full"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full"><line x1="0" x2="100" y1="25" y2="25" stroke="#e2e8f0" strokeDasharray="2 2"/><line x1="0" x2="100" y1="50" y2="50" stroke="#e2e8f0" strokeDasharray="2 2"/><line x1="0" x2="100" y1="75" y2="75" stroke="#e2e8f0" strokeDasharray="2 2"/>{points.length > 1 && <path d={`${path} L ${points.at(-1)?.x} 100 L ${points[0].x} 100 Z`} fill="#d1fae5"/>}<path d={path} fill="none" stroke="#047857" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/>{points.map((point, index) => <circle key={index} cx={point.x} cy={point.y} r="1.5" fill="white" stroke="#047857" strokeWidth="1" vectorEffect="non-scaling-stroke"/>)}</svg></div></CardContent></Card><Card className="mt-7 border-slate-200 shadow-sm"><CardHeader><CardTitle>Historial de check-ins</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Fecha</th><th className="pb-3">Peso medio</th><th className="pb-3">Cintura</th><th className="pb-3">Fuerza</th><th className="pb-3">Alcohol</th></tr></thead><tbody>{[...checkins].reverse().map((item) => <tr key={item.recordedAt} className="border-b border-slate-100 last:border-0"><td className="py-4 text-slate-600">{new Date(item.recordedAt).toLocaleDateString("es-ES")}</td><td className="py-4 font-semibold text-slate-900">{item.weeklyWeight} kg</td><td className="py-4 text-slate-600">{item.waist} cm</td><td className="py-4 text-slate-600">{item.strength} sesiones</td><td className="py-4 text-slate-600">{item.alcohol} ml</td></tr>)}</tbody></table></CardContent></Card></>}</PageLayout>;
}
function Metric({ icon: Icon, label, value, detail }: { icon: typeof Scale; label: string; value: string; detail: string }) { return <Card className="border-slate-200 shadow-sm"><CardContent className="p-5"><Icon className="mb-4 size-5 text-emerald-700"/><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></CardContent></Card>; }
function EmptyProgress() { return <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Scale className="mx-auto size-7 text-emerald-700"/><h2 className="mt-4 text-lg font-semibold text-slate-900">Aún no hay check-ins guardados</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Completa el primero y aquí empezaremos a construir tu tendencia real de peso, cintura y adherencia.</p></div>; }
