"use client";

import { ChangeEvent, useEffect, useState } from "react";
import Image from "next/image";
import { Camera, ImagePlus, RotateCcw } from "lucide-react";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { Card, CardContent } from "@/components/ui/card";
const views = [{ id: "front", label: "Frente", hint: "Relajado, sin posar" }, { id: "left", label: "Perfil izquierdo", hint: "Brazos relajados" }, { id: "back", label: "Espalda", hint: "Postura natural" }, { id: "right", label: "Perfil derecho", hint: "Brazos relajados" }];
type Photos = Record<string, string>;
function openPhotoDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open("athlos", 1); request.onupgradeneeded = () => request.result.createObjectStore("photos"); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function readPhotos() { const db = await openPhotoDb(); return new Promise<Photos>((resolve, reject) => { const request = db.transaction("photos").objectStore("photos").get("monthly"); request.onsuccess = () => resolve(request.result ?? {}); request.onerror = () => reject(request.error); }); }
async function writePhotos(photos: Photos) { const db = await openPhotoDb(); return new Promise<void>((resolve, reject) => { const request = db.transaction("photos", "readwrite").objectStore("photos").put(photos, "monthly"); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); }
export default function PhotosPage() { const [photos, setPhotos] = useState<Photos>({}); const [loaded, setLoaded] = useState(false); useEffect(() => { readPhotos().then(setPhotos).catch(() => undefined).finally(() => setLoaded(true)); }, []); function updatePhotos(next: Photos) { setPhotos(next); writePhotos(next).catch(() => undefined); } function addPhoto(event: ChangeEvent<HTMLInputElement>, id: string) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => updatePhotos({ ...photos, [id]: String(reader.result) }); reader.readAsDataURL(file); } return <div className="min-h-screen bg-slate-50"><AppSidebar /><main className="lg:pl-72"><div className="mx-auto max-w-6xl px-4 py-7 sm:px-8 lg:px-10"><header className="mb-8"><p className="mb-2 text-sm font-semibold text-emerald-700">EVOLUCIÓN FÍSICA</p><h1 className="text-3xl font-bold tracking-tight text-slate-950">Fotos mensuales</h1><p className="mt-2 max-w-2xl text-slate-600">Hazlas por la mañana, con la misma luz, distancia y ropa. Busca consistencia: las fotos no tienen que ser bonitas, tienen que ser comparables.</p></header><Card className="mb-6 border-sky-200 bg-sky-50 shadow-none"><CardContent className="flex gap-3 p-5"><Camera className="mt-0.5 size-5 shrink-0 text-sky-700"/><p className="text-sm leading-6 text-sky-950">Tus imágenes se guardan únicamente en este navegador. Cuando conectemos Supabase, podrás guardar una copia privada en la nube.</p></CardContent></Card><section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{views.map(({ id, label, hint }) => <div key={id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="relative aspect-[3/4] bg-slate-100">{photos[id] ? <Image src={photos[id]} alt={`Foto ${label}`} fill unoptimized className="object-cover"/> : <label className="flex h-full cursor-pointer flex-col items-center justify-center gap-3 p-5 text-center text-slate-500 transition hover:bg-slate-50"><ImagePlus className="size-7 text-emerald-700"/><span className="text-sm font-semibold text-slate-700">{loaded ? "Subir foto" : "Cargando…"}</span><input onChange={(event) => addPhoto(event, id)} accept="image/*" type="file" className="sr-only"/></label>}</div><div className="flex items-center justify-between p-4"><div><p className="font-semibold text-slate-900">{label}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></div>{photos[id] && <button onClick={() => { const next = { ...photos }; delete next[id]; updatePhotos(next); }} aria-label={`Eliminar foto ${label}`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><RotateCcw className="size-4"/></button>}</div></div>)}</section></div></main></div>; }
